### ISSUE TITLE
[BUG]:  Modify JSON Config via GUI Even When Stream Deck is Disconnected

### ISSUE THREAD

**Issue by neutropico** [streamdeck-linux-gui/streamdeck-linux-gui#233] opened 2024-11-14 18:20 UTC
### In raising this issue I confirm that

- [X] I have fully completed the issue template
- [X] I have searched open and closed issues for duplicates
- [X] I have read the [Contribution Guidelines](https://streamdeck-linux-gui.github.io/streamdeck-linux-gui/contributing/contributing-guide/)
- [X] I have read the [Code of Conduct](https://streamdeck-linux-gui.github.io/streamdeck-linux-gui/contributing/code-of-conduct/)
- [X] I have read the [Documentation](https://streamdeck-linux-gui.github.io/streamdeck-linux-gui/)

### Describe the bug

Hello,

I am currently using streamdeck-ui to manage my Stream Deck settings, and I have created a Python application that reads the JSON configuration file to create a dock-like interface on my laptop when I'm away from home. However, I have encountered a limitation: I cannot modify the JSON configuration through the GUI when the Stream Deck is not connected via USB.

I would like to suggest adding a feature or altering the existing functionality so that users can edit the JSON configuration directly from the GUI, even when the Stream Deck is disconnected. This would enable more flexibility for users who wish to modify their configurations on the go.

### Steps to reproduce the behavior

-

### Expected behavior

    Loading the Configuration: Allow the application to load the JSON configuration file even if the Stream Deck is not connected.

    Editing Capabilities: Provide the ability to edit all configuration options through the GUI, regardless of the connection status.

    Save Functionality: Ensure that any changes made in the GUI can be saved back to the JSON file seamlessly.

    Graceful Handling: Display a warning or message if certain functionalities are not available due to the Stream Deck being disconnected, while still allowing for editing.

### System Information

-

**Comment by coolapso** [comment] 2024-11-14 18:38
hi! thanks for reaching out,  but  this is not a bug and no action is going to be taken. 

 please read: https://github.com/streamdeck-linux-gui/streamdeck-linux-gui/discussions/203
 
 Closing.

**Closed by coolapso** 2024-11-14 18:38 UTC
Labels: wontfix
