### ISSUE TITLE
[BUG]:  Write text is cutting off the first 12 or 12 characters

### ISSUE THREAD

**Issue by insidesources** [streamdeck-linux-gui/streamdeck-linux-gui#150] opened 2024-01-11 22:36 UTC
### In raising this issue I confirm that

- [X] I have fully completed the issue template
- [X] I have searched open and closed issues for duplicates
- [X] I have read the [Contribution Guidelines](https://streamdeck-linux-gui.github.io/streamdeck-linux-gui/contributing/contributing-guide/)
- [X] I have read the [Code of Conduct](https://streamdeck-linux-gui.github.io/streamdeck-linux-gui/contributing/code-of-conduct/)
- [X] I have read the [Documentation](https://streamdeck-linux-gui.github.io/streamdeck-linux-gui/)

### Describe the bug

I have a button with write text in it, when i press the button, the first 11-12 characters of the text is cut off and doesn't get typed. this was working until today
![2024-01-11-173410_213x103_scrot](https://github.com/streamdeck-linux-gui/streamdeck-linux-gui/assets/56140662/5ae4002d-0b4a-49ce-b122-9351e3eeb0db)

### Steps to reproduce the behavior

configure write text, press button in notepad, compare text from write text you configured in streamdeckui

### Expected behavior

write the entire write text box

### Screenshots

![2024-01-11-172822_413x868_scrot](https://github.com/streamdeck-linux-gui/streamdeck-linux-gui/assets/56140662/81b722d7-7ed2-44f5-9523-7dd2e7af0259)

### System Information

arch linux, qtile, python 3.11.6-1, streamdeck-ui 4.1.0-1(from aur) and python-elgato-streamdeck 0.9.5-1(also from aur)

### Stream Deck Version

streamdeck XL

**Comment by insidesources** [comment] 2024-01-11 22:37
the number of characters that gets cut off changes, it was 11-12 and in the screenshot, its only the first 4

**Comment by ajbucci** [comment] 2024-01-15 17:42
Are you running qtile in x11 or wayland?

**Comment by insidesources** [comment] 2024-01-15 18:04
> Are you running qtile in x11 or wayland?

X11

**Comment by ajbucci** [comment] 2024-01-27 18:39
Strange. I've fixed a few other bugs related to press/write keys that were recently merged to main. I don't think they would fix your issue but since I can't reproduce it it's worth a check. Are you comfortable installing from source to see if your issue is resolved?

**Closed** 2024-02-07 18:01 UTC
Labels: bug
